apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dce.fullname" . }}
data:
  alphavantage.url: {{ .Values.alphavantage.url }}
  alphavantage.symbol: {{ .Values.alphavantage.symbol }}
  alphavantage.market: {{ .Values.alphavantage.market }}